from __future__ import annotations

from django.db import models


class UploadedDataset(models.Model):
	"""Uploaded OHLCV datasets stored in media/ for repeatable analysis."""

	file = models.FileField(upload_to="datasets/%Y/%m/")
	original_name = models.CharField(max_length=255)
	row_count = models.PositiveIntegerField(default=0)
	column_snapshot = models.JSONField(default=list, blank=True)
	uploaded_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ["-uploaded_at", "-id"]

	def __str__(self) -> str:
		return self.original_name or self.file.name


class BacktestResult(models.Model):
	"""Persisted summary of a strategy run and its derived analytics."""

	dataset = models.ForeignKey(
		UploadedDataset,
		on_delete=models.CASCADE,
		related_name="backtest_results",
	)
	symbol = models.CharField(max_length=64, default="SYMBOL")
	strategy_name = models.CharField(max_length=64)
	parameters = models.JSONField(default=dict, blank=True)
	profit = models.DecimalField(max_digits=18, decimal_places=2, default=0)
	trade_count = models.PositiveIntegerField(default=0)
	metrics = models.JSONField(default=dict, blank=True)
	price_payload = models.JSONField(default=list, blank=True)
	indicator_payload = models.JSONField(default=dict, blank=True)
	signal_payload = models.JSONField(default=list, blank=True)
	equity_curve = models.JSONField(default=list, blank=True)
	monte_carlo_payload = models.JSONField(default=dict, blank=True)
	paper_trading_payload = models.JSONField(default=dict, blank=True)
	created_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ["-created_at", "-id"]

	def __str__(self) -> str:
		return f"{self.strategy_name} | {self.symbol} | {self.created_at:%Y-%m-%d %H:%M}"


class Trade(models.Model):
	"""Closed trade generated by the backtesting engine."""

	LONG = "LONG"
	BUY = "BUY"
	SELL = "SELL"
	SIDE_CHOICES = [(LONG, "Long"), (BUY, "Buy"), (SELL, "Sell")]

	backtest_result = models.ForeignKey(
		BacktestResult,
		on_delete=models.CASCADE,
		related_name="trades",
	)
	symbol = models.CharField(max_length=64)
	side = models.CharField(max_length=4, choices=SIDE_CHOICES)
	entry_date = models.DateTimeField()
	exit_date = models.DateTimeField()
	entry_price = models.DecimalField(max_digits=18, decimal_places=4)
	exit_price = models.DecimalField(max_digits=18, decimal_places=4)
	quantity = models.PositiveIntegerField(default=1)
	profit = models.DecimalField(max_digits=18, decimal_places=2, default=0)
	profit_pct = models.DecimalField(max_digits=10, decimal_places=4, default=0)
	exit_reason = models.CharField(max_length=32, default="signal")
	created_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ["entry_date", "id"]

	def __str__(self) -> str:
		return f"{self.symbol} {self.side} {self.quantity}"


class Portfolio(models.Model):
	"""Paper trading portfolio snapshot linked to a completed analysis run."""

	backtest_result = models.OneToOneField(
		BacktestResult,
		on_delete=models.CASCADE,
		related_name="portfolio",
		null=True,
		blank=True,
	)
	name = models.CharField(max_length=128, default="Kinetic Paper Portfolio")
	initial_balance = models.DecimalField(max_digits=18, decimal_places=2, default=100000)
	balance = models.DecimalField(max_digits=18, decimal_places=2, default=100000)
	realized_pnl = models.DecimalField(max_digits=18, decimal_places=2, default=0)
	positions = models.JSONField(default=dict, blank=True)
	equity_curve = models.JSONField(default=list, blank=True)
	is_active = models.BooleanField(default=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ["-updated_at", "-id"]

	def __str__(self) -> str:
		return self.name
