# Generated by Django 6.0.3 on 2026-04-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='SYMBOL', max_length=64)),
                ('strategy_name', models.CharField(max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('trade_count', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('price_payload', models.JSONField(blank=True, default=list)),
                ('indicator_payload', models.JSONField(blank=True, default=dict)),
                ('signal_payload', models.JSONField(blank=True, default=list)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('monte_carlo_payload', models.JSONField(blank=True, default=dict)),
                ('paper_trading_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_snapshot', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kinetic Paper Portfolio', max_length=128)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=100000, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=100000, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('positions', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backtest_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='trading.backtestresult')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('profit_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('exit_reason', models.CharField(default='signal', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.backtestresult')),
            ],
            options={
                'ordering': ['entry_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to='trading.uploadeddataset'),
        ),
    ]
